options=[["East Antarctica","Verkhoyansk","North Ice","Denali"],["K2","Kangchenjunga","Nanda Devi","Kamet"],["Santoro Kangri","Kamet","Trisul","Kangchenjunga"],
["Africa","Asia","North America","Europe"],["China","India","United States","Indonesia"],["Cheetah","Pronghorn","Spur winged Goose","Peregrine Falcon"],["Nilgiri Biopshere Reserve","Cold Desert, Himachal Pradesh","Nanda Devi, Uttrakhand","Panna, Madhya Pradesh"],["Hydrogen","Helium","Lithium","Beryllium"],
["Rajasthan","Madhya Pradesh","Maharashtra","Uttar Pradesh"],["Diamond","Lonsdaleite","Dyneema","Buckypaper"],["Ganga","Narmada","Yamuna","Kaveri"],["Australia","Africa","Europe","North America"],["Banana","Apple","Mango","Guava"],["Rose","Lotus","Sunflower","Tulip"],["Sphygmomanometer","Glucometer","Stethoscope","Pulse Oximeter"],
["America","India","France","Argentina"],["Saiga","Camel","Scorpion","Yucca Moth"],["Elephant","Shark","Blue Whale","Rhinoceros"],["Femur","Ankle Bone","Shin Bone","Ribs"],["Tiger","Lion","Wolf","Elephant"],["Sparrow","Eagle","Peacock","Pelican"],["Australia","Europe","Africa","Asia"],["France","Ukraine","Russia","Morocco"],
["APJ Abdul Kalam","Dr.B.R Amedkar","Mahatma Gandhi","Subhaschandra Bose"],["Mango Tree","Banyan Tree","Neem Tree","Sandalwood Tree"],["Wular Lake","Vamembanad Lake","Loktak Lake","Dal Lake"],["Pacific Ocean","Indian Ocean","Atlantic Ocean","Southern ocean"],["Bhagat Singh","Mahatma Gandhi","Narendra Modi","Jawaharlal Nehru"],
["India And Bangladesh","India And Pakistan","India And China","India And Nepal"],["Marra Plateau","Deccan Plateau","Putorana Plateau","Tibetan Plateau"],["Ganga","Narmada","Yamuna","Kaveri"],["Amarkantak","Western Himalaya","Brahmagiri Mountain","Western Ghats Mountain"],["Tropic of cancer","Tropic of Capricon","Equator","Prime Meridian"],["Nile river","Amazon river","Yangtze river","Yellow river"],
["Tooth Decay","Diabetes","Asthma","Hypertension"],["Skin","Tongue","Eyes","Nose"],["English","Mandarin Chinese","Spanish","French"],["Mandarin Chinese","English","Spanish","Hindi"],["Sun","Proxima Centauri","Sirius","Alpha Centauri A"],["Solar Energy","Geothermal Energy","Wind energy","Hydropower"],["New Delhi","Kolkata","Pune","Chennai"],
["50 stars","41 stars","45 stars","55 stars"],["1945","1932","1959","1950"],["1837 to 1901","1800 to 1870","1820 to 1850","1830 to 1890"],["Shah Jahan","Akbar","Humayun","Aurangzeb"],["Demeter","Zeus","Poseidon","Apollo"],["Theodore Roosevelt","Jimmy Carter","John F.Kennedy","George Bush"],["Julia Gilliard","Mary Robinson","Kim Campbell","Ruth Perry"],
["1431","1478","1400","1326"],["1776","1700","1799","1800"],["Abraham Lincoln","Gerrit Smith","Theodare Parker","Thomas WentWorth Higginson"],["I.N.S Chakra","I.N.S Vikram","I.N.S Arihant","I.N.S Arighat"],["K.V.K Sundram","Shri Rajiv Kumar ","Sushil Chandra","Sukumar Sen"],["University Of Mumbai","Nalanda University","University of Calcutta","University of Madras"],["Rajasthan","Maharashtra","Tirupur","Tamil Nadu"],["Khan Abdul Ghaffar Khan","Mother Teresa","Nelson Mandela","Mike Tyson"],
["Kolkata","Mumbai","Delhi","Chennai"],["Its gravitational pull is not strong enough","It does not have gravity","No sound can be heard","There is no air and water on moon"],["J.B Lamarck","Darwin","Weisman","De Vries"],["Earth"s Gravitational Pull","Earth"s Magnetic Pull","Moon"s Gravitational Pull","Moon"s Magnetic Pull"],["A heavy shower of rain","Ice Cubes","Boiled water","Distilled Water"],["Biochemistry","Applied Science","Forensic Science","Criminalogy"],["Conservation of mass","Conservation of energy","Conservation of momentum","Conservation of heat"],
["iNCOVACC","Covaxin","Covidshield","Coronil"],["Andhra Pradesh","Uttar Pradesh","Himachal Pradesh","Uttarakhand"],["Tata MD","Reliance","Serum Institute","Johnson and Johnson"],["Hinduism","Sikkism","Buddhism","Jainism"],["Justice Indu Malhotra","Justice Dhananjaya Y.Chandrachud","Justice Sanjay Kishan Kaul","Justice Pankaj Mithal"],["Turkenminstan","Europe","Canada","Germany"],["Andaman & Nicobar","Jammu & Kashmir","Ladakh","Pudducherry"],["Uttar Pradesh","Kerala","Assam","Telangana"],["United States Of America","Israel","Russia","China"],["Shashi Shekhar Vempati","Vikram Mehra","Arnab Goswami","Vineet Seth"],
["Hyderabad","Goa","Mumbai","Kolkata"],["Netaji Subhash Chandra Bose","Sadar Vallabhbhai Patel","Lal Bahadur Shastri","Chandra Shekhar Azad"],["Africa","Nepal","Brazil","Myanmar"],["Egypt","South Africa","South Sudan","Afghanistan"],["K Radhakrishnan","Mridul Hazarika","Bharat Bhaskar","Sanjay Kumar"],["Parker Solar Probe","Falcon Heavy","Saturn V","The Soyuz"],["Indian Army","Special Forces of Indian Army","Indian Navy","Indian Airforce"],["5","3","2","0"],["November 9","December 5","January 23","June 18"],["1997","1987","2001","2000"],["5.8%","8.2%","8.9%","4.7%"],
["NTPC Limited","Tata Power","JSW Energy","NHPC"],["6.2%","4.9%","8.5%","3.7%"],["Tata Power Solar System","Adani Power","NLC India","JSW Energy Ltd"],["Partap Chauhan","Tanuja Nesari","Haarshaali Malhotra","Nalini Saligram"],["Sabala Organization","NITI Aayog","Women’s Indian Association","ActionAid"],["Mrinal Sen","S S Rajamouli","Madhu C. Narayanan","Ram Gopal Verma"],["Brajendra Navnit","J S Deepak","Aashish Chandorkar","Anup Wadhawan"],["N V Chalapathi","Ashok Sahni","M A Atmanand","Indra Sekhar Sen"],
["Schneider Electric","IDE Technologies","Xylem","Va Tech Wabag"],["Unified Payment Interface","Vajra","CCAvenue","Infibeam"],["Indian Space Research Organisation(ISRO)","European Space Agency(ESA)","National Aeronautics and Space Administration(NASA)","Japan Aerospace Exploration Agency(JAXA)"],["JNCASR","IASLC","CancerCare","LUNGevity"],["4 March","19 November","11 October","24 January"],["Mumbai","Jerusalem","New York","Chandigarh"],["Assam","Arunachal Pradesh","Rajasthan","Himachal Pradesh"],["ICE Futures- Europe","Tri-Partite Technology","Kakatiya Energy system","CBOE Global Markets"],
["Cricket","Volleyball","Basketball","kabaddi"],["Asia Cup","Uber Cup","Women"s Cup","Champions Cup"],["nine","seven","twelve","fifteen"],#Options related to sports
["2010","2009","2011","2008"],["English","Hindi","Italian","Chinese"],["Pooja Gehlot","Mirabai Chanu","Sakshi Malik","Vinesh Malik"],
["Field Hockey","Horse Racing","Table Tennis","Show Jumping"],["Spain","France","UK","Pakistan"],["Hockey","Tennis","Chess","Cricket"],
["2010 Africa Cup of Nations","FIFA World Cup","Indian Premier League -III","T-20 World Cup"],["Polo","Golf","Chess","Billiards"],
["Mumbai Gold Cup","Everest Cup","Merdeka Cup","V.C.C. Cup"],["Bobby Riggs","Don Budge","Rod Laver","Fred Stolle"],["Australia","Canada","England","France"],
["Rani Rampal","Siddhi Singh","Savita Punia","Birajani Ekka"],["Chamonix","London","San Francisco","Paris"],["Dominica","The Bahamas","Dominican Republic","Trinidad and Tabago"],
["20 meter long","22 meter long","24 meter long","26 meter long"],["An English Cricketer","An English Footballer","An English Golfer","An English Tennis Player"],
["Australia","England","New Zealand","South Africa"],["Kane Williamson","Shakib Al Hasan","David Warner","Rohit Sharma"],["Katrina Keenan","Lyn Fullston","Jackie Lord","Jane Smit"],
["1987 Cricket World Cup","1992 Cricket World Cup","1996 Cricket World Cup","1999 Cricket World Cup"],["10","11","12","13"],["Bangladesh","Iran","India","South Korea"],
["Basketball","Football","Volleyball","Ice Hockey"],["Two","Three","Four","Five"],,
["Football","Cricket","Hockey","Tennis"],["Chappell & Co","Garrard & Co","Marylebone & Co","Adelaide & Co"],["1933 Olympics","1934 Olympics","1935 Olympics","1936 Olympics"],
["Iran","India","Bangladesh","South Korea"],["Turkey","Bahrain","Saudi Arabia","Malaysia"],["6","8","10","12"],["1988 Olympic Games","1992 Olympic Games","1996 Olympic Games","2000 Olympic Games"],
["Yugoslavia Vs United States of America","Uruguay Vs Argentina","France Vs Mexico","Uruguay Vs United States Of America"],["England","United States of America","Netherlands","Sweden"],
["An American tennis player","A French tennis player","An Australian tennis player","A Canadian tennis player"],["Tennis","Polo","Badminton","Baseball"],
["Serena Williams","Steffi Graf","Margaret Court","Billie Jean King"],["As an Indian Football Player","As an Indian tennis player","As an Indian cricket player","As an Indian Badminton player"],
["Prakash Padukone","Chetan Anand","Pullela Gopichand","Parupalli Kashyap"],["Greece","Spain","Italy","Sweden"],["Australia","United States Of America","Spain","Belgium"],
["Tennis","Badminton","Table Tennis","Squash"],["Paul Drinkhall and Liam Pitchford","Sharath Achanta and Sathiyan Gnanasekaran","Harmeet Desai and Sanil Shankar Shetty","Anthony Amalraj and Harmeet Desai"],
["Alan Shepard","Jack Nicklaus","Arnold Palmer","Tiger Woods"],["Tennis","Cricket","Basketball","Golf"],["Bianca Pagdanganan","Liu Wenbo","Du Mohan","Yuka Saso"],
["Jack Broughton","John L. Sullivan","Daniel Mendoza","John Graham Chambers"],
["Deoxyribonucliec Acid","Ribonucliec Acid","Daily News Analysis","Double Network Artery"],["206","200","302","306"],["Stephan Hawking","James Clerk Maxwell","Albert Einstein","Sir Isaac Newton"],["Graphite","Diamond","Iron","Steel"],["Nitrogen","Sulphur","Argon","Hydrogen"],["98%","60%","90%","10%"],["Hydrogen","Argon","Nitrogen","Carbon Dioxide"],["8 minutes","8 hours","8 seconds","8 days"],["Stephan Hawkin","Albert Einstein","Isaac Newton","James Clerk Maxwell"],["-48","-30","-40","-59"],  #This line onwards sciene questions started
["Australia","Russia","Canada","Poland"],["Pluto","Jupiter","Venus","Mars"],["Mass Number","Atomic Number","Coordination number","Molecule Number"],["33","35","37","39"],["Sputnik 1","Explorer 1","Vanguard 1","Bhaskara 2"],["Spiritual Oath","Charaka Oath","Ethical Oath","Hippocratic Oath"],["Conductor","Insulator","Graphite","Semi conductor"],["Apollo 15","Apollo 11","Apollo 12","Apollo 13"],["31","33","32","36"],["Entomology","Botany","Zoology","Mycology"],["10 brains,4 hearts","9 brains,3 hearts","6 brains,6 hearts","4 brains,5 hearts"],
["K","M","J","L"],["Cheetah","Tiger","Lion","Leopard"],["2","4","42","46"],["Laser Amplitude By Stimulated Emission Of Radiation","Laser Amplification By Stimulated Emission Of Radiation","Laser Amplification By Stimulated Absorption Of Radiation","Laser Applied By Stimulated Erosion Of Radiation"],["Circumference","Boundary","Border","Yard"],["False","True","Maybe","Data irrelevant"],["Pacific Ocean","Indian Ocean","Atlantic Ocean","Artic Ocean"],["Sputnik 1","Explorer 1","SACA","Copernicus"],["Tim Berner Lee","Bob Kahn","David Filo","Ray Tomlinson"],
["True","False","Maybe","Data Irrelevant"],["Ear","Nose","Knee","Wrist"],["0","10","25","30"],["Brain Freeze","Spicy Reaction","Reflex","Knee Jerk"],["Universal Serial Bus","Unique Serial Bus","Universal Series Bus","Unique Standard Bus"],["Sahara Desert","Thar Desert","Gobi Desert","Namib Desert"],["2010","1999","2011","2015"],["Skin","Liver","Brain","Lungs"],["Ab-ve","O-ve","A-ve","B-ve"],["2006","2003","2010","2012"],["Antarctic Blue Whale","African Elephant","Saltwater Crocodile","Sperm Whale"],["Mount Vesuvius","Mount Etna","Mount Merapi","Mount Yasur"],
["Peeling skin","Cracking fingers","Hiccups","Sleep Positon"],["243","190","200","278"],["4","1","5","3"],["Radiation","Pressure","Force","Luminous Intensity"],["Moons","Asteroids","Meteorites","Comet"],["1970","1955","1879","1920"],["Silver","Aluminium","Copper","Brass"],["Small Pox","Black Plague","Tuberculosis","Diphtheria"]]

answers=["East Antarctica","K2","Santoro Kangri","Africa","China","Cheetah","Nilgiri Biopshere Reserve","Hydrogen","Rajasthan","Diamond","Ganga","Africa","Mango","Lotus","Sphygmomanometer","India","Camel","Blue whale","Femur","Lion","Peacock","Asia","Russia","Dr. B.R. Ambedkar","Banyan Tree","Wular Lake","Pacific Ocean","Mahatma Gandhi","India and Pakistan","Tibetan Plateau","Ganga","Amarkantak","Tropic of Cancer","Nile river","Tooth Decay","Skin","English","Mandarin Chinese","Sun","Solar Energy","New Delhi","50 stars","1945","1837 to 1901","Shah Jahan","Demeter","Theodore Roosevelt","Julia Gilliard",
"1431","1776","Abraham Lincoln","I.N.S Chakra","Sukumar Sen","Nalanda University","Tirupur","Khan Abdul Ghaffar Khan","Kolkata","Its gravitational pull is not strong enough","J. B. Lamarck","Earth"s Gravitational Pull","A heavy shower of rain","Forensic Science","Conservation of momentum","iNCOVACC","Andhra Pradesh","Tata MD","Sikhism","Justice Indu Malhotra","Turkenminstan","Puducherry","Kerala","Russia","Shashi Shekhar Vempati","Kolkata","Sardar Vallabhbhai Patel","Africa","South Sudan","K Radhakrishnan","Falcon Heavy","Indian Army","Three","9 November","2000","5.8%","NTPC Limited",
"8.5%","NLC India","Partap Chauhan","NITI Aayog","Madhu C. Narayanan","Brajendra Navnit","Ashok Sahni","Va Tech Wabag","Vajra","National Aeronautics and Space Administration (NASA)","JNCASR","24 January","Mumbai","Himachal Pradesh","ICE Futures- Europe",
"Lawn Tennis","Uber Cup","15","2010","English and French","Sakshi Malik","Horse Racing","Pakistan","Cricket","Indian Premier League -III","Golf","Merdeka Cup","Don Budge","France","Savita Punia","Chamonix","Trinidad and Tobago","22 meter long","An English Cricketer","England","Rohit Sharma","Lyn Fullston","1992 Cricket World Cup","10","India",
"Basketball","Four","England","Cricket","Garrard & Co","1936 Olympics","India","Malaysia","6","1996 Olympic Games","Uruguay Vs Argentina","United States of America","A French tennis player","Tennis","Serena Williams","As an Indian badminton player","Prakash Padukone","Greece","United States of America","Table Tennis","Paul Drinkhall and Liam Pitchford","Arnold Palmer","Golf","Bianca Pagdanganan","John Graham Chambers","Deoxyribonucleic acid","206","Sir Isaac Newton","Diamond","Nitrogen","98 percent","Nitrogen","8 minutes",
"Stephen Hawking","-40","Poland","Jupiter","Atomic Number","33","Sputnik 1","Hippocratic Oath","Insulator",
"Apollo 15","32","Micology","9 brains, 3 hearts","J","Cheetah","2",
"Light Amplification by Stimulated Emission of Radiaton","The circumference","False","The Pacific","Sputnik",
"Tim Berners-Lee","True","The ear","Zero","Brain freeze","Universal Serial Bus","Antartica","2010","The liver",
"AB Negative","2006","The Antarctic blue whale","Mount Vesuvius","Peeling skin","243",
"4","Radiation","Moons","1970","Silver","Small Pox"]


#Test Program with input
aa=input()
for i in range(len(options)):
    if aa in answers[i] and aa in options[i]:
        print("Correct Answer")
        break
    elif aa not in answers[i] and aa not in options[i]:
        print("Wrong Answer")
    else:
        print("Wrong answer")
